# Generated by Django 4.2.4 on 2023-08-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dvisual_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvisual_config_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('logo_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('key_param', models.JSONField()),
                ('d_type', models.JSONField()),
            ],
            options={
                'db_table': 'dvisual_config',
            },
        ),
        migrations.CreateModel(
            name='dvisual_config_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_str', models.JSONField()),
                ('dvisual_config_detail', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True, null=True)),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dvisual_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvisual_config_id', to='Dvisual_app.dvisual_config')),
            ],
            options={
                'db_table': 'dvisual_config_detail',
            },
        ),
        migrations.CreateModel(
            name='dvisual_report_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvisual_report_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('action', models.CharField(max_length=200)),
                ('workbook_name', models.CharField(max_length=200)),
                ('dvisual_config_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvisual_config_detail_id', to='Dvisual_app.dvisual_config_detail')),
            ],
            options={
                'db_table': 'dvisual_report',
            },
        ),
    ]
