# Generated by Django 4.2.4 on 2023-08-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dvisual_app', '0004_remove_dvisual_report_api_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvisual_report_api',
            name='action',
        ),
    ]
