# Generated by Django 4.2.4 on 2023-08-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dvisual_app', '0010_alter_dvisual_report_api_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dvisual_report_api',
            new_name='dvisual_report_api_link',
        ),
        migrations.AlterModelTable(
            name='dvisual_report_api_link',
            table='dvisual_report_link',
        ),
    ]
