# Generated by Django 4.2.4 on 2023-08-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dvisual_app', '0011_rename_dvisual_report_api_dvisual_report_api_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dvisual_report_api_l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvisual_report_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('workbook_name', models.CharField(max_length=200)),
                ('link', models.URLField(null=True)),
                ('dvisual_config_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvisual', to='Dvisual_app.dvisual_config_detail')),
            ],
            options={
                'db_table': 'dvisual_report_l',
            },
        ),
        migrations.DeleteModel(
            name='dvisual_report_api_link',
        ),
    ]
