# Generated by Django 4.2.4 on 2023-08-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dvisual_app', '0012_dvisual_report_api_l_delete_dvisual_report_api_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_1', models.CharField(null=True)),
            ],
            options={
                'db_table': 'pdf_link',
            },
        ),
    ]
