# Generated by Django 4.2.4 on 2023-08-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dvisual_app', '0013_pdf_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvisual_report_api_l',
            name='link',
        ),
    ]
