# Generated by Django 4.2.4 on 2023-08-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dvisual_app', '0014_remove_dvisual_report_api_l_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='d_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_1', models.CharField(null=True)),
            ],
            options={
                'db_table': 'd_link',
            },
        ),
        migrations.CreateModel(
            name='dvisual_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvisual_report_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('workbook_name', models.CharField(max_length=200)),
                ('dvisual_config_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvisual', to='Dvisual_app.dvisual_config_detail')),
            ],
            options={
                'db_table': 'dvisual_report',
            },
        ),
        migrations.RemoveField(
            model_name='dvisual_report_api_l',
            name='dvisual_config_detail_id',
        ),
        migrations.DeleteModel(
            name='pdf_link',
        ),
        migrations.DeleteModel(
            name='dvisual_report_api_l',
        ),
        migrations.AddField(
            model_name='d_link',
            name='dvisual_report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='Dvisual_app.dvisual_report'),
        ),
    ]
