# Generated by Django 4.2.4 on 2023-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dvisual_app', '0015_d_link_dvisual_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_link',
            name='dvisual_report_id',
        ),
        migrations.AddField(
            model_name='dvisual_report',
            name='link',
            field=models.CharField(null=True),
        ),
    ]
