# Generated by Django 4.2.4 on 2023-08-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dvisual_app', '0016_remove_d_link_dvisual_report_id_dvisual_report_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvisual_report',
            name='link',
        ),
        migrations.AddField(
            model_name='d_link',
            name='dvisual_report_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='Dvisual_app.dvisual_report'),
            preserve_default=False,
        ),
    ]
