# Generated by Django 4.2.4 on 2023-08-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dvisual_app', '0017_remove_dvisual_report_link_d_link_dvisual_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvisual_report',
            name='r_link',
            field=models.CharField(null=True),
        ),
    ]
